UMS/UMS/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :students do
    collection do
      get 'search'
    end
  end

  resources :sections do
    collection do
      get 'search'
    end
  end

  resources :semesters do
    collection do
      get 'search'
    end
  end

  resources :courses do
    collection do
      get 'search'
    end
  end

  resources :departments do
    collection do
      get 'search'
    end
  end

  resources :professors do
    collection do
      get 'search'
    end
  end

  root to: "welcome#index"
end

UMS/UMS/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

UMS/UMS/app/helpers/application_helper.rb
module ApplicationHelper
end

UMS/UMS/app/views/application/_home_and_logout.html.erb
<table>
  <tr>
    <td><%= link_to 'Home', root_path %></td>
    <td><%= link_to 'Log out',   destroy_user_session_path,method: :delete%></td>
  </tr>
</table>

<%= render "navigation_bar"%>

UMS/UMS/app/views/application/_navigation_bar.html.erb
<table>
    <tr>
        <td><%= link_to 'Students', students_path %></td>
        <td><%= link_to 'Semesters', semesters_path %></td>
        <td><%= link_to 'Sections', sections_path %></td>
        <td><%= link_to 'Professors', professors_path %></td>
        <td><%= link_to 'Departments', departments_path %></td>
        <td><%= link_to 'Courses', courses_path %></td>
    </tr>
</table>