UMS/UMS/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :students do
    collection do
      get 'search'
    end
  end

  resources :sections do
    collection do
      get 'search'
    end
  end

  resources :semesters do
    collection do
      get 'search'
    end
  end

  resources :courses do
    collection do
      get 'search'
    end
  end

  resources :departments do
    collection do
      get 'search'
    end
  end

  resources :professors do
    collection do
      get 'search'
    end
  end

  root to: "welcome#index"
end

UMS/UMS/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  belongs_to :professor
  belongs_to :semester
  has_and_belongs_to_many :students

  validates :course, presence:true
  validates_associated :course
  validates :professor, presence:true
  validates_associated :professor
  validates :semester, presence:true
  validates_associated :semester
end

UMS/UMS/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  def search
    @courses = Course.all
    @sections = Section.joins(:course).where('courses.number LIKE ?', "%#{params[:query]}%")
    render :index
  end

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
    @students = Student.all
  end

  # GET /sections/1/edit
  def edit
    @students = Student.all
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:course_id, :professor_id, :year, :semester_id, :student_ids => [])
    end
end

UMS/UMS/app/helpers/sections_helper.rb
module SectionsHelper
end

UMS/UMS/app/views/sections/_form.html.erb
<%= render "home_and_logout"%>

<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :course_id %>
    <%#= form.text_field :course_id %>
    <%= form.collection_select :course_id, Course.all, :id, :number%>
  </div>

  <div class="field">
    <%= form.label :professor_id %>
    <%#= form.text_field :professor_id %>
    <%= form.collection_select :professor_id, Professor.all, :id, :name%>

  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :semester_id %>
    <%#= form.text_field :semester_id %>
    <%= form.collection_select :semester_id, Semester.all, :id, :semester%>
  </div>

  <div class="field">
    <%= form.label :student_id %><br>
    <%= form.collection_check_boxes(:student_ids, @students, :id, :name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

UMS/UMS/app/views/sections/edit.html.erb
<%= render "home_and_logout"%>

<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

UMS/UMS/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "home_and_logout"%>

<h1>Sections</h1>

<%= form_tag(search_sections_url, method: "get") do %>
  <%= label_tag(:query, "Search by Course Number:") %>
  <%= text_field_tag(:query) %>
  <%= submit_tag("Search") %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Professor</th>
      <th>Year</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.course.number %></td>
        <td><%= section.professor.name %></td>
        <td><%= section.year %></td>
        <td><%= section.semester.semester %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

UMS/UMS/app/views/sections/new.html.erb
<%= render "home_and_logout"%>

<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

UMS/UMS/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "home_and_logout"%>

<p>
  <strong>Course:</strong>
  <%= @section.course.number %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @section.professor.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @section.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @section.semester.semester %>
</p>

<p>
  <strong>Students:</strong>
</p>
<ul>
  <% @section.students.each do |student| %>
    <li> <b>Name</b>: <%= student.name %>,  <b>Number</b>:  <%= student.identifier %></li>
<% end %>
</ul>


<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>